# Default theme settings; site overrides live in _config.shiro.yml.
menu: []

site:
  favicon: /favicon.svg
  rss:
    enabled: false
    path: /atom.xml

article:
  # Whether to display the TOC button in the post page
  show_toc: true

# Analytics
analytics:
  # Only support Google Analytics 4
  google:
    enabled: false
    id: ""
  # Microsoft Clarity
  clarity:
    enabled: true
    id: "vzb6r72095"

# Comment systems
comments:
  enabled: false
  provider: disqus
  disqus:
    shortname: ""

# Excerpt settings
excerpt:
  # If post has <!-- more -->, use it.
  # Otherwise fallback to auto-truncated excerpt.
  fallback:
    enabled: true
    length: 200
journal:
  motto: '致广大，尽精微。'
